blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class newPost(FlaskForm):
	title = StringField(label='Title', validators=[DataRequired()])
	content = TextAreaField(label='Content', validators=[DataRequired()])
	submit = SubmitField(label='Post')

blog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from blog import db
from blog.posts.forms import newPost
from blog.models import Post
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

@posts.route('/newpost', methods=['GET', 'POST'])
@login_required
def newpost():
	form = newPost()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Blog has been posted!', category='success')
		return redirect(url_for('main.home'))
	return render_template('newpost.html', title='New Post', form = form, legend='New Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def updatepost(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = newPost()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash('Blog has been updated!!', category='success')
		return redirect(url_for('posts.post', post_id = post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('newpost.html', title='Update Post', form = form, legend ='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def deletepost(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Blog has been deleted!', category='success')
	return redirect(url_for('main.home'))

blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from blog import db, bcrypt
from blog.users.forms import Reg, Login, Update
from blog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from blog.users.utils import save_pic

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = Reg()
	if form.validate_on_submit():
		hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data , email=form.email.data, password=hash_password)
		db.session.add(user)
		db.session.commit()
		flash('Account has been created! Log in to access your account!', category='success')
		return redirect(url_for('users.login'))
	return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
	form = Login()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember = form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Log in unsuccessful! Please check Email and Password', 'danger')
	return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.home')) 

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
	form = Update()
	if form.validate_on_submit():
		if form.picture.data:
			pic_file = save_pic(form.picture.data)
			current_user.img = pic_file

		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Account has been updated!', category='success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email
	img = url_for('static', filename='IMG/' + current_user.img)
	return render_template('account.html', title='Account', img=img, form =form)

@users.route('/user/<string:username>')
def user_posts(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
	return render_template('user_posts.html' , posts=posts, user=user  )

blog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{img}}">
	    <div class="media-body">
	      <h2>{{ current_user.username }}</h2>
	      <p class="text-secondary">{{ current_user.email  }}</p>
	    </div>
	  </div>
	  <form method='POST', enctype="multipart/form-data">
		    {{ form.hidden_tag() }}
            <hr>    
            <h4 class="text-center">Details</h4><br>
                
            {{ form.username.label() }}
            {% if form.username.errors %}
                {{ form.username( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username( class="form-control" )}}
            {% endif %}
            <br>
              
            {{ form.email.label() }}
            {% if form.email.errors %}
                {{ form.email( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email( class="form-control" )}}
            {% endif %}
            <br>
            
            {{ form.picture.label() }}
            {{ form.picture( class="form-control-file ") }}
            {% if form.picture.errors %}
            	{% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span><br>
                {% endfor %}
            {% endif %}

            <br>
            <div class="text-center">
                {{ form.submit( class="btn btn-outline-info" )}}
            </div>
            <br>
		</form>
	</div>
{% endblock %}

blog/templates/home.html
{% extends 'layout.html' %}
{% block content %}
	{% for post in posts.items %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ url_for('static', filename='IMG/' + post.author.img) }}">
		  <div class="media-body">
		    <div class="article-metadata" >
		      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
		      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
		    </div>
		    <h3><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h3>
		    <p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if posts.page == page_num %}
				<a class="btn btn-secondary" href="{{ url_for('main.home' , page=page_num) }}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-secondary" href="{{ url_for('main.home' , page=page_num) }}">{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

	{% if title %}
		<title>{{title}}</title>
	{% else %}
		<title>Blog</title>
	{% endif %}
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="/">Flask Blog</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
	          <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	          {% if current_user.is_authenticated %}
	          	  <a class="nav-item nav-link" href="{{ url_for('posts.newpost') }}">New Post</a>
	          	  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>	
	          {% else %}
		          <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
		          <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
		      {% endif %}
	        </div>
	      </div>
	    </div>
	</nav>
	<div role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	        {% with messages = get_flashed_messages(with_categories=true) %}
		      {% if messages %}
		        {% for category, msg in messages %}
		          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
		            {{ msg }}
		            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> </button> 
		          </div>
		        {% endfor %}
		      {%endif %}
		    {% endwith %}
	        {% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Latest Posts</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Calendars</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>
	</div> 
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
		<form method='POST'>
		    {{ form.hidden_tag() }}
                
            <h2 class="text-center">Log In</h2><br>

            {{ form.email.label() }}
            {% if form.email.errors %}
                {{ form.email( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email( class="form-control" )}}
            {% endif %}
              
            {{ form.password.label() }}
            {% if form.password.errors %}
                {{ form.password( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password( class="form-control" )}}
            {% endif %}
            <br>

            <div class="form-check ml-2">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div> 
            <br>
            <div class="text-center">
                {{ form.submit( class="btn btn-outline-info" )}}
            </div>
            
            <br>
            <div class="text-center">
                <h6>Need an account?
                    <a class="btn btn-outline-secondary btn-sm" href="{{ url_for('users.register') }}">Sign Up</a>
                </h6>
            </div>
		</form>
	</div>
{% endblock %}

blog/templates/newpost.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
		<form method='POST'>
		    {{ form.hidden_tag() }}
                
            <h2 class="text-center">{{legend}}</h2><br>

            {{ form.title.label() }}
            {% if form.title.errors %}
                {{ form.title( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.title( class="form-control" )}}
            {% endif %}
            <br>  
            {{ form.content.label() }}
            {% if form.content.errors %}
                {{ form.content( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.content( class="form-control" )}}
            {% endif %}
            <br>
            <br>
            <div class="text-center">
                {{ form.submit( class="btn btn-outline-info" )}}
            </div>
            <br>
		</form>
	</div> 
{% endblock %}

blog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ url_for('static', filename='IMG/' + post.author.img) }}">
		  <div class="media-body">
		    <div class="article-metadata row" >
		      <div class="col">
		      	<a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
		      	<small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
		      </div>
		      <div class="col d-md-flex justify-content-md-end">
			      {% if post.author == current_user %}
			        <a class="btn btn-outline-secondary btn-sm m-1 me-md-2" href="{{ url_for('posts.updatepost', post_id=post.id) }}">Update</a>
			        <button type="button" class="btn btn-outline-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
			      {% endif %}
		      </div>
		    </div>
		    <h3 class="article-title">{{ post.title }}</h3>
		    <p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
		<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="deleteModalLabel">Delete Blog ?</h5>
		        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
		      </div>
		      <div class="modal-body">
		        This will permanently delete your Blog.
		      </div>
		      <div class="modal-footer">
		      	<form action="{{ url_for('posts.deletepost', post_id=post.id) }}" method="POST">
		          <input type="submit" class="btn btn-outline-danger" value="Delete">
		        </form>
		      </div>
		    </div>
		  </div>
		</div>
{% endblock %}

blog/templates/register.html
{% extends 'layout.html' %}
{% block content %}
	<div class="content-section">
		<form method='POST'>
		    {{ form.hidden_tag() }}
                
            <h2 class="text-center">Join Today</h2><br>
                
            {{ form.username.label() }}
            {% if form.username.errors %}
                {{ form.username( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.username( class="form-control" )}}
            {% endif %}
            
              
            {{ form.email.label() }}
            {% if form.email.errors %}
                {{ form.email( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.email( class="form-control" )}}
            {% endif %}
              
            {{ form.password.label() }}
            {% if form.password.errors %}
                {{ form.password( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.password( class="form-control" )}}
            {% endif %}
                
            {{ form.confirm_password.label() }}
            {% if form.confirm_password.errors %}
                {{ form.confirm_password( class="form-control is-invalid" )}}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.confirm_password( class="form-control" )}}
            {% endif %}
                
            <br><br>
            <div class="text-center">
                {{ form.submit( class="btn btn-outline-info" )}}
            </div>
            <br>
            <div class="text-center">
                <h6>Already have an account?
                    <a class="btn btn-outline-secondary btn-sm" href="{{ url_for('users.login') }}">Login</a>
                </h6>
            </div>
		</form>
	</div>
{% endblock %}

blog/templates/user_posts.html
{% extends 'layout.html' %}
{% block content %}
	<h4 class="mb-3">Blogs created by {{user.username}} ({{posts.total}})</h4>
	{% for post in posts.items %}
		<article class="media content-section">
		  <img class="rounded-circle article-img" src="{{ url_for('static', filename='IMG/' + post.author.img) }}">
		  <div class="media-body">
		    <div class="article-metadata" >
		      <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
		      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
		    </div>
		    <h3><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h3>
		    <p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if posts.page == page_num %}
				<a class="btn btn-secondary" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-secondary" href="{{ url_for('users.user_posts', username=user.username , page=page_num) }}">{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock %}